name: tfsec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: tfsec check
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: .
        version: latest
        format: default
        soft_fail: true
